spring:
  config:
    import: optional:credentials/secretes.properties
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:DIGITOX;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
  flyway:
    enabled: false
#logging:
#  level:
#    root: debug

application:
  security:
    jwt:
      secrete: ${JWT_SECRETE}
  user:
    image:
      default-profile: https://via.placeholder.com/150
      default-banner: https://via.placeholder.com/400x200
